# SwiftLint Configuration for MindGrowee

# Exclude generated files
excluded:
  - .build
  - DerivedData
  - "**/Generated"

# Disable rules that don't fit our style
disabled_rules:
  - trailing_whitespace
  - line_length
  - force_try
  - force_cast

# Opt-in rules
opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces

# Rule configurations
line_length:
  warning: 150
  error: 200

function_body_length:
  warning: 80
  error: 120

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 600
  error: 800

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

# Custom rules
custom_rules:
  no_print:
    name: "No print statements"
    regex: "print\\("
    message: "Use Logger.shared instead of print"
    severity: warning
  
  no_nslog:
    name: "No NSLog"
    regex: "NSLog\\("
    message: "Use Logger.shared instead of NSLog"
    severity: error
